### PR TITLE
Fix perturbation model

### LINKED ISSUE #153: Incomplete change of dynamic model during `simulate`
In the `simulate` command the parameter `integrator.f` is changed in a callback. 

https://github.com/JuliaEnergy/PowerDynamics.jl/blob/44dd0a65ec0cd7c45afc0352be5db9963ab852b6/src/faults/AbstractPerturbation.jl#L54-L59

This is not officially supported and might lead to problems since refrerences to the original function might be scattered all over the place inside the ODEProblem. On problem we are currently aware of: the rhs won't be updated for gradient calculations inside `Rodas4` and probably other implicit solver algorithms. See issue #149, especially [this MWE](https://github.com/JuliaEnergy/PowerDynamics.jl/issues/149#issuecomment-825494028).
One hotfix is to add
```juluia
integrator.f = newf
integrator.cache.tf.f = integrator.f
```
which would update the function ref for the gradient as well. However, I am not sure whether it is smart to go down that rabbit hole. At this point we're meddling with internal stuff which could have weird consequences.

### PR DESCRIPTION
**Pull request by lindnemi**
I tried a number of things to fix #153 . This will also be necessary to restore compatibility with https://github.com/PIK-ICoNe/NetworkDynamics.jl/pull/91, which eliminates allocations and thus speeds up the solvers.

Strangely `find_valid_initial_condition` now fails sometimes when it didn't before and causes some test to fail.

Using the dynamic solver instead leads to incorrect results in some other tests. (I don't know it that's a really bug or just reflect the fact that the dynamical solver and the nonlinear solver find different states)

I settled on combining both approaches with a try statement. However, a bug in the IEEE model remains. TBC

### CODE REVIEW

**Comment by lindnemi** [comment]
Fixed the issue. The mass_matrix got lost on the way leading to wrong results. Now everything works including the test with `find_valid_initial_condition`. IMO this branch can be merged:

Caveat: PowerDynamics does not use the DIffEq parameter interface at the moment. I realized the perturbation by introducing a boolean parameter that is false during the perturbed state and true during the initial state.

If further versions of PD want to use the parameter interface, we might need to change the AbstractPerturbation a little. There is plenty of opportunities, e.g. wrapping the parameters in a tuple or using https://diffeq.sciml.ai/stable/features/diffeq_arrays/#DEDataArrays.

**Comment by lindnemi** [comment]
The new ND version will blow up type signatures, I am not sure how to change that and hope it is not a problem :sweat_smile:

File: src/faults/AbstractPerturbation.jl [hunk 1]
```diff
@@ -48,21 +48,26 @@ function simulate(np::AbstractPerturbation, powergrid::PowerGrid, x1::Array, tim
     @assert np.tspan_fault[2] <= last(timespan) "fault cannot end in the future"
 
     np_powergrid = np(powergrid)
+    regular = rhs(powergrid)
+    error = rhs(np_powergrid)
+    _f = (dx, x, p, t) -> p ? regular(dx,x,p,t) : error(dx,x,p,t)
+
+    f = ODEFunction(_f, mass_matrix = regular.mass_matrix, syms = regular.syms)
```
Comment (hexaeder) [inline src/faults/AbstractPerturbation.jl:55]: Are there abstract pertubations which change the size of the system/the mass matrix?

File: src/faults/AbstractPerturbation.jl [hunk 2]
```diff
@@ -48,21 +48,26 @@ function simulate(np::AbstractPerturbation, powergrid::PowerGrid, x1::Array, tim
     @assert np.tspan_fault[2] <= last(timespan) "fault cannot end in the future"
 
     np_powergrid = np(powergrid)
+    regular = rhs(powergrid)
+    error = rhs(np_powergrid)
+    _f = (dx, x, p, t) -> p ? regular(dx,x,p,t) : error(dx,x,p,t)
```
Comment (hexaeder) [inline src/faults/AbstractPerturbation.jl:53]:
```suggestion
    _f = (dx, x, p, t) -> p ? regular(dx,x,nothing,t) : error(dx,x,nothing,t)
```
I wouldn't pass on the parameter since it is more of an implementation detail.

File: src/faults/AbstractPerturbation.jl [hunk 3]
```diff
@@ -72,7 +77,7 @@ function simulate(np::AbstractPerturbation, powergrid::PowerGrid, x1::Array, tim
     cb2 = DiscreteCallback(((u,t,integrator) -> t in np.tspan_fault[2]), regularState)
```
Comment (hexaeder) [inline src/faults/AbstractPerturbation.jl:77]: I think we should use [PresetTimeCallbacks](https://diffeq.sciml.ai/stable/features/callback_library/#PresetTimeCallback) instead. They will trigger only once and at the exact same time. Otherwise one needs to make sure that the fault times are actually visited by the solver?

**Review by hexaeder — COMMENTED** [review]
Nice! This solution is suprisingly easy :)

File: src/faults/AbstractPerturbation.jl (hunk 1 above)
Comment (antonplietzsch) [reply src/faults/AbstractPerturbation.jl:55]: In theory yes. `LineFailure` is a subtype of `AbstactPerturbation`. So if we have a system with dynamic lines, this failure would indeed change the system size. There is no test for this specific situation so far and I am not sure this even worked before.
However, I am not sure how meaningful it would be to actually support that case. If you go down to model the electromagnetic transients in your line, you would maybe also need a more detailed model for the failure than just a vanishing line from one moment to the other.

File: src/faults/AbstractPerturbation.jl (hunk 3 above)
Comment (antonplietzsch) [reply src/faults/AbstractPerturbation.jl:77]: @hexaeder Sounds good. Could you make a commit for that?

File: src/faults/AbstractPerturbation.jl (hunk 1 above)
Comment (hexaeder) [reply src/faults/AbstractPerturbation.jl:55]: I've asked on slack an there is no way to change the mass matrix yet. So it is not really possible to `resize!` DAE integrators right now. 
This would also complicate things a lot since the mapping of symbols to indices in the state vector would go bad. IMO topology changes should be modeled within the original topology: i.e. set the current of a vanished line to 0.
Maybe we could add a check that there is no dimension missmatch between error and normal state.

**Review by antonplietzsch — APPROVED** [review]

**Comment by lindnemi** [comment]
Thanks for taking care of the details while I was away! Anton, could you release a new minor version? Afterwards, I'll merge the allocation fix into ND and release a new version there as well
